meta_product_name: "Skatespots"
meta_title: "Skatespots - Find skate spots nearby"
meta_description: "Find skatespots nearby or in faraway places and access unique spots and skateparks around the world."
meta_image: "cover.jpg"         # should exist in `app/assets/images/`
twitter_account: "@shanlongjj"   # required for Twitter Cards
